version: "3.8"

services:
  app:
    build: .
    container_name: evelynlettering_app
    restart: always
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://letteringdigital:Dhiogo1123581321345589@db:5432/evelynlettering_production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    volumes:
      - ./storage:/app/storage
      - ./log:/rails/log
      - ./tmp:/rails/tmp
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["sh", "-c", "bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec rails server -b 0.0.0.0"]

  db:
    image: postgres:latest
    container_name: evelynlettering_db
    restart: always
    environment:
      POSTGRES_USER: letteringdigital
      POSTGRES_PASSWORD: Dhiogo1123581321345589
      POSTGRES_DB: evelynlettering_production
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
